<div class="clientLogo">
        <div class="container">
            <h3>Know About Our Brand Partnerships</h3>
            <p>Hard Disk Direct is the top-tier IT hardware supplier, working collaboratively with a wide range of leading tech manufacturers for complete IT Hardware Solutions.</p>

            <div class="Logos">
                <img src='<?php echo $this->getViewFileUrl('images/clientlogo.png'); ?>' alt="-" class="img-responsive" />
            </div>
            <!-- #Logos -->
        </div>
        <!-- container -->
    </div>
    <!-- #clientLogo -->

    <div class="container">
        <div class="col-md-3">
            <div class="footer-logo">
                <a href="javascript:;"><img src='<?php echo $this->getViewFileUrl('images/footer-logo.png'); ?>' alt="-" class="img-responsive" /></a>
            </div>
            <!-- #footer-logo -->
            <ul class="addressList">
                <li><a href="https://maps.google.com/?q=111 North Euclid St Suite A Fullerton CA 92832"><span class="fas fa-map-marker"></span> 111 North Euclid St Suite A Fullerton CA 92832</a></li>
                <li><a href="tel:+1-888-898-8012"><span class="fas fa-phone"></span> +1-888-898-8012</a></li>
                <li><a href="mailto:Sales@m4l.com"><span class="fas fa-envelope"></span> Sales@m4l.com</a></li>
            </ul>

        </div>
        <!-- col-md-3 -->

        <div class="col-md-3">
            <h3>Information</h3>
            <ul class="footerMenu">
                <li><a href="<?php echo $this->getUrl('customer/account/login/') ?>">About Us</a></li>
                <li><a href="javascript:;">Privacy Policy</a></li>
                <li><a href="javascript:;">Returns Policies &amp; Procedures</a></li>
                <li><a href="javascript:;">Shipping Policy</a></li>
                <li><a href="javascript:;">Sitemap</a></li>
            </ul>
        </div>
        <!-- col-md-3 -->


        <div class="col-md-1">
            <h3>Brands</h3>
            <ul class="footerMenu">
                <li><a href="javascript:;">Hp</a></li>
                <li><a href="javascript:;">Dell</a></li>
                <li><a href="javascript:;">IBM</a></li>
                <li><a href="javascript:;">Seagate</a></li>
                <li><a href="javascript:;">Intel</a></li>
                <li><a href="javascript:;">View All</a></li>
            </ul>
        </div>
        <!-- col-md-1 -->


        <div class="col-md-2">
            <h3>All Categories</h3>
            <ul class="footerMenu">
                <li><a href="javascript:;">Memory</a></li>
                <li><a href="javascript:;">Sorage</a></li>
                <li><a href="javascript:;">CPU's Processors</a></li>
                <li><a href="javascript:;">Network Accessories</a></li>
                <li><a href="javascript:;">Solid State Storage</a></li>
                <li><a href="javascript:;">View All</a></li>
            </ul>
        </div>
        <!-- col-md-2 -->


        <div class="col-md-3">
            <h3>Follow Us</h3>
            <div class="socialIcons">
                <a href="https://www.facebook.com/"><span class="fab fa-facebook-f"></span></a>
                <a href="https://twitter.com/?lang=en"><span class="fab fa-twitter"></span></a>
                <a href="javascript:;"><span class="fab fa-instagram"></span></a>
                <a href="javascript:;"><span class="fab fa-youtube"></span></a>
            </div>
            <!-- socialIcons -->
        </div>
        <!-- col-md-2 -->
    </div>

<!-- footer -->
