<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Files.LineLength.MaxExceeded
// phpcs:disable Magento2.Security.LanguageConstruct.DirectOutput

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>

<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
?>

<div class="category">
    <?php echo $this->getLayer()->getCurrentCategory()->getName() ?>
</div>

<?php if (!$_productCollection->count()) :?>
    <p class="message note"><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></p>
<?php else :?>

<?= $block->getToolbarHtml() ?>
<?= $block->getAdditionalHtml() ?>
<?php
if ($block->getMode() == 'grid') {
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $showDescription = false;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
} else {
    $viewMode = 'list';
    $image = 'category_page_list';
    $showDescription = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
}
?>

<div class="catalogListWrap">
    <ul class="catalogList">
        <?php foreach ($_productCollection as $_product) :?>
        <li>
            <div class="row">
                <div class="col-md-3">
                    <div class="productImg">
                        <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class="product photo">
                            <?= $block->getImage($_product, $image)->toHtml() ?>
                        </a>
                    </div>
                    <!-- #productImg -->
                </div>
                <!-- #col-md-3 -->

                <div class="col-md-6">
                    <div class="productTxt">
                        <?php

                        $info = [];
                        $info['name'] = '<strong class="product name">'
                            . ' <a href="' . $block->escapeUrl($_product->getProductUrl()) . '" title="'
                                . $block->stripTags($_product->getName(), null, true) . '">'
                                . $_helper->productAttribute($_product, $_product->getName(), 'name')
                                . '</a></strong>';

                        $info['button'] = $_product->getIsSalable() ?   '<div class="stock available"><span>' . $block->escapeHtml(__('In stock')) . '</span></div>' :
                            '<div class="stock unavailable"><span>' . $block->escapeHtml(__('Out of stock')) . '</span></div>';

                        $info['links'] = '<div class="product links" data-role="add-to-links">'
                            . '<a href="#" data-post=\'' . $this->helper(Magento\Wishlist\Helper\Data::class)->getAddParams($_product) . '\' class="action towishlist" data-action="add-to-wishlist">'
                                . '<span>' . $block->escapeHtml(__('Add to Wishlist')) . '</span></a></div>';

                        if ($_product->isSaleable()) {
                            $info['addToCart'] = '<button type="button" title="' . $block->escapeHtmlAttr(__('Add to Cart')) . '" class="action tocart"'
                                . ' data-mage-init=\'{ "redirectUrl": { "event": "click", url: "' . $block->escapeUrl($block->getAddToCartUrl($_product)) . '"} }\'>'
                                . '<span>' . $block->escapeHtml(__('Add to Cart')) . '</span></button>';
                        }

                        $price = $_product->getPrice();
                        $specialPrice = $_product->getSpecialPrice();
                        $saving = $price - $specialPrice;

                        ?>

                        <h3 class="productName"><?php echo $info['name'] ?></h3>
                        <h4>Features</h4>
                        <ul class="productFeature">
                            <li>Mfr Part#: <?php echo $block->escapeHtmlAttr($_product->getSku()); ?></li>
                            <li>MFR: <?php echo $_product->getAttributeText('manufacturer'); ?> </li>
                        </ul>

                        <p><strong>Available:</strong> <span class="StockStatus"></span><?php echo $info['button'] ?></p>

                        <a href="javascript:;" class="wishList"><span class="far fa-heart"></span> <?php echo $info['links'] ?> </a>
                    </div>
                    <!-- #productTxt -->
                </div>
                <!-- #col-md-6 -->

                <div class="col-md-3">
                    <div class="pricingDetails">
                        <div class="productPrice">$<?php echo number_format($_product->getSpecialPrice(), 2) ?></div>
                        <div class="WasPrice">Price: <span>$<?php echo number_format($_product->getPrice(), 2)  ?></span></div>
                        <div class="SavingPrice">Saving: <span>$<?php echo number_format($saving, 2)  ?></span></div>
                       <?php
                       $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                       $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
                        ?>
                        <button class="action tocart primary"
                                  data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                  type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart1') ?>">
                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                        </button>
                    </div>
                    <!-- pricingDetails -->
                </div>
                <!-- #col-md-3-->
            </div>
            <!-- #row -->
        </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
